### ISSUE TITLE
Handling Keyevent directly 

### ISSUE THREAD

**Issue by hisakaz0** [tSU-RooT/ringot#1]
現状，キーイベントのハンドリングが`termbox.Event`を`swtich`文で直接制御しています．これだと，1つの動作(アクション)にEventタイプが異なるkeyeventを2つ以上記述するとき，ちょっち面倒です．
### Example

``` go
switch ev.Key {
  case termbox.KeyArrowUp :
    // do A action

swtich ev.Ch {
  case 'j'
    // do A action
```

**Comment by tSU-RooT** [comment]
こんにちは、ご指摘ありがとうございます。
とりあえずこれは間に合わせの実装で、作っていた時は
将来的にキーバインドをコンフィグでいじれるようにした時にもっといい書き方に
変えようと思っていたんですが、まだ実装していない感じです。

**Comment by hisakaz0** [comment]
@tSU-RooT あ，はい．一応，`keybind.go`でキーバインドを変更できるようにしました． #2 でプルリク出しました．よければどうぞ．
